{% set name = "freshwater" %}
{% set version = "0.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/freshwater-{{ version }}.tar.gz
  sha256: 9442b73be7ffc9cfeaf04285698d701b6ae08ea34c075f895fa73797878a1be1

build:
  number: 1
  noarch: python
  script:
    - rm -rf pyproject.toml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python {{ python_min }}
  run:
    - numpy >=1.19.1,<2.0.0
    - python >={{ python_min }},<4.0

test:
  imports:
    - freshwater
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/danielrobb/freshwater
  summary: Python module for estimating thermodynamic properties of water in freshwater lakes.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xeulha
